### PR TITLE
Ameba fixes and Apatite::Matrix use

### PR DESCRIPTION
**Pull request by rmarronnier**
I'm trying to learn about neural networks and this library is incredibly educational. Thanks for sharing this !
I couldn't help myself but made some fixes (mostly Ameba suggested) and replaced the `PtrMatrix` with the one from `Apatite`. I saw no performance issues and could make `Shainet` benefit from already written methods.

Hope you find this weird PR useful :-)

### CODE REVIEW

**Comment by rmarronnier** [comment]
I have no idea why the specs fail on Travis :/

**Comment by bararchy** [comment]
I guess we haven't really touched the CI part in a while, let me try to pass specs locally

**Comment by bararchy** [comment]
Seems it fails on the rprop run, not the most stable one for sure.... we might want to remote Rprop from specs as it's a bad optimzer anyway, @ArtLinkov what say you?

**Comment by rmarronnier** [comment]
Thanks for looking into this. All specs (except the ones already commented out in master) pass for me locally. It's strange that this one fails on Travis.

**Comment by ArtLinkov** [comment]
@rmarronnier first, let me say I'm happy you find SHAInet useful and thank you for contributing, Regarding the specs, if I'm not mistaken the rprop spec is the one that fails. In that case, you can just comment it out because it is quite volatile (converges fast but sometime to local minima) and doesn't work very well with small datasets

**Comment by rmarronnier** [comment]
Thanks @ArtLinkov for the explanation. I commented out the failing spec. I hope it's not too essential and that it was not a safeguard against any possible regression.

**Comment by bararchy** [comment]
@rmarronnier I believe it should be OK now.
Merging.

**Pull request merged**
